### ISSUE TITLE
Refactoring code of duplicate scale and json rpc codes

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia.go#8]
https://github.com/darwinia-network/darwinia.go/pull/7#issuecomment-620280755

https://github.com/darwinia-network/darwinia.go/pull/7#pullrequestreview-401303927

**Comment by clearloop** [comment]
It's a big update of `darwinia.js` because `darwinia.js` has to request `web3 API` for twice time if there isn't a process interaction with `darwinia.go` with a dirty **long JSON string**.

+ `darwinia.js` will keep the codec part but not shadow service in javascript
  + Will contain a go-lang shadow service port
+ `darwinia.js` will delete the database part 
  + the `sqlite3` of `@darwinia/dj` is hard to install for `npm` or `yarn`
  + most of time I install `@darwinia/dj` failed because of the `sqlite3`


## Why darwinia.go
Most of the services in `@darwinia/dj` can be moved into `dargo` actually, doesn't write golang at the beginning because we doesn't have the `ethashproof` part at that time, and there is an `darwinia.js` no need to open a new repo.

**The `ethashproof` in `darwinia.go` is much better than the origin one embeded in `tranvictor/ethashproof`**

In a word, services without interacting with `darwinia-node` should be written in Golang, because of the verbose and dirty dependencies of javascript, because of the dynamic feature of javascript...(Writing Javascript is much harder than writing Golang, the typecheck in javascript just is...hard, and wasting times)


### What can `darwinia.js` do

The irreplaceable part of `darwinia.js` is it can interact with darwinia-node, this feature `darwinia.go` will never reach.

**Comment by clearloop** [comment]
Supported in #7
